// Generated by gencpp from file intention_application/Array.msg
// DO NOT EDIT!


#ifndef INTENTION_APPLICATION_MESSAGE_ARRAY_H
#define INTENTION_APPLICATION_MESSAGE_ARRAY_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace intention_application
{
template <class ContainerAllocator>
struct Array_
{
  typedef Array_<ContainerAllocator> Type;

  Array_()
    : x(0)
    , y(0)
    , intention(false)  {
    }
  Array_(const ContainerAllocator& _alloc)
    : x(0)
    , y(0)
    , intention(false)  {
  (void)_alloc;
    }



   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;

   typedef uint8_t _intention_type;
  _intention_type intention;





  typedef boost::shared_ptr< ::intention_application::Array_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intention_application::Array_<ContainerAllocator> const> ConstPtr;

}; // struct Array_

typedef ::intention_application::Array_<std::allocator<void> > Array;

typedef boost::shared_ptr< ::intention_application::Array > ArrayPtr;
typedef boost::shared_ptr< ::intention_application::Array const> ArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intention_application::Array_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intention_application::Array_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::intention_application::Array_<ContainerAllocator1> & lhs, const ::intention_application::Array_<ContainerAllocator2> & rhs)
{
  return lhs.x == rhs.x &&
    lhs.y == rhs.y &&
    lhs.intention == rhs.intention;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::intention_application::Array_<ContainerAllocator1> & lhs, const ::intention_application::Array_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace intention_application

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::intention_application::Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intention_application::Array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intention_application::Array_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intention_application::Array_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intention_application::Array_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intention_application::Array_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intention_application::Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d6d4ea0cfc5344e240c5b9bd523fcbef";
  }

  static const char* value(const ::intention_application::Array_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd6d4ea0cfc5344e2ULL;
  static const uint64_t static_value2 = 0x40c5b9bd523fcbefULL;
};

template<class ContainerAllocator>
struct DataType< ::intention_application::Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intention_application/Array";
  }

  static const char* value(const ::intention_application::Array_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intention_application::Array_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 x\n"
"int32 y\n"
"bool intention\n"
;
  }

  static const char* value(const ::intention_application::Array_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intention_application::Array_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.intention);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Array_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intention_application::Array_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intention_application::Array_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
    s << indent << "intention: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.intention);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTENTION_APPLICATION_MESSAGE_ARRAY_H
