// Generated by gencpp from file intention_application/snapshotResponse.msg
// DO NOT EDIT!


#ifndef INTENTION_APPLICATION_MESSAGE_SNAPSHOTRESPONSE_H
#define INTENTION_APPLICATION_MESSAGE_SNAPSHOTRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace intention_application
{
template <class ContainerAllocator>
struct snapshotResponse_
{
  typedef snapshotResponse_<ContainerAllocator> Type;

  snapshotResponse_()
    : data(false)  {
    }
  snapshotResponse_(const ContainerAllocator& _alloc)
    : data(false)  {
  (void)_alloc;
    }



   typedef uint8_t _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::intention_application::snapshotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intention_application::snapshotResponse_<ContainerAllocator> const> ConstPtr;

}; // struct snapshotResponse_

typedef ::intention_application::snapshotResponse_<std::allocator<void> > snapshotResponse;

typedef boost::shared_ptr< ::intention_application::snapshotResponse > snapshotResponsePtr;
typedef boost::shared_ptr< ::intention_application::snapshotResponse const> snapshotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intention_application::snapshotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intention_application::snapshotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::intention_application::snapshotResponse_<ContainerAllocator1> & lhs, const ::intention_application::snapshotResponse_<ContainerAllocator2> & rhs)
{
  return lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::intention_application::snapshotResponse_<ContainerAllocator1> & lhs, const ::intention_application::snapshotResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace intention_application

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::intention_application::snapshotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intention_application::snapshotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intention_application::snapshotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intention_application::snapshotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intention_application::snapshotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intention_application::snapshotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intention_application::snapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::intention_application::snapshotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b94c1b53db61fb6ULL;
  static const uint64_t static_value2 = 0xaed406028ad6332aULL;
};

template<class ContainerAllocator>
struct DataType< ::intention_application::snapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intention_application/snapshotResponse";
  }

  static const char* value(const ::intention_application::snapshotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intention_application::snapshotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool data\n"
"\n"
;
  }

  static const char* value(const ::intention_application::snapshotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intention_application::snapshotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct snapshotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intention_application::snapshotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::intention_application::snapshotResponse_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // INTENTION_APPLICATION_MESSAGE_SNAPSHOTRESPONSE_H
