// Generated by gencpp from file intention_application/snapshot.msg
// DO NOT EDIT!


#ifndef INTENTION_APPLICATION_MESSAGE_SNAPSHOT_H
#define INTENTION_APPLICATION_MESSAGE_SNAPSHOT_H

#include <ros/service_traits.h>


#include <intention_application/snapshotRequest.h>
#include <intention_application/snapshotResponse.h>


namespace intention_application
{

struct snapshot
{

typedef snapshotRequest Request;
typedef snapshotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct snapshot
} // namespace intention_application


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::intention_application::snapshot > {
  static const char* value()
  {
    return "8b94c1b53db61fb6aed406028ad6332a";
  }

  static const char* value(const ::intention_application::snapshot&) { return value(); }
};

template<>
struct DataType< ::intention_application::snapshot > {
  static const char* value()
  {
    return "intention_application/snapshot";
  }

  static const char* value(const ::intention_application::snapshot&) { return value(); }
};


// service_traits::MD5Sum< ::intention_application::snapshotRequest> should match
// service_traits::MD5Sum< ::intention_application::snapshot >
template<>
struct MD5Sum< ::intention_application::snapshotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::intention_application::snapshot >::value();
  }
  static const char* value(const ::intention_application::snapshotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::intention_application::snapshotRequest> should match
// service_traits::DataType< ::intention_application::snapshot >
template<>
struct DataType< ::intention_application::snapshotRequest>
{
  static const char* value()
  {
    return DataType< ::intention_application::snapshot >::value();
  }
  static const char* value(const ::intention_application::snapshotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::intention_application::snapshotResponse> should match
// service_traits::MD5Sum< ::intention_application::snapshot >
template<>
struct MD5Sum< ::intention_application::snapshotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::intention_application::snapshot >::value();
  }
  static const char* value(const ::intention_application::snapshotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::intention_application::snapshotResponse> should match
// service_traits::DataType< ::intention_application::snapshot >
template<>
struct DataType< ::intention_application::snapshotResponse>
{
  static const char* value()
  {
    return DataType< ::intention_application::snapshot >::value();
  }
  static const char* value(const ::intention_application::snapshotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // INTENTION_APPLICATION_MESSAGE_SNAPSHOT_H
