// Generated by gencpp from file intention_application/snapshotRequest.msg
// DO NOT EDIT!


#ifndef INTENTION_APPLICATION_MESSAGE_SNAPSHOTREQUEST_H
#define INTENTION_APPLICATION_MESSAGE_SNAPSHOTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace intention_application
{
template <class ContainerAllocator>
struct snapshotRequest_
{
  typedef snapshotRequest_<ContainerAllocator> Type;

  snapshotRequest_()
    {
    }
  snapshotRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::intention_application::snapshotRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::intention_application::snapshotRequest_<ContainerAllocator> const> ConstPtr;

}; // struct snapshotRequest_

typedef ::intention_application::snapshotRequest_<std::allocator<void> > snapshotRequest;

typedef boost::shared_ptr< ::intention_application::snapshotRequest > snapshotRequestPtr;
typedef boost::shared_ptr< ::intention_application::snapshotRequest const> snapshotRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::intention_application::snapshotRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::intention_application::snapshotRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace intention_application

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::intention_application::snapshotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::intention_application::snapshotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intention_application::snapshotRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::intention_application::snapshotRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intention_application::snapshotRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::intention_application::snapshotRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::intention_application::snapshotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::intention_application::snapshotRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::intention_application::snapshotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "intention_application/snapshotRequest";
  }

  static const char* value(const ::intention_application::snapshotRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::intention_application::snapshotRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::intention_application::snapshotRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::intention_application::snapshotRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct snapshotRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::intention_application::snapshotRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::intention_application::snapshotRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // INTENTION_APPLICATION_MESSAGE_SNAPSHOTREQUEST_H
